FROM nginx:alpine

# Másold a statikus fájlokat a frontend build könyvtárából
COPY --from=frontend /app/build /usr/share/nginx/html

# Expose az nginx által használt port
EXPOSE 80

# Indítsd el az nginx szervert
CMD ["nginx", "-g", "daemon off;"]
