spring.application.name=AIWebshop
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=aiwebshop
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.AIWebshop.AIWebshop=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE
jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.ai.openai.api-key=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

